# Copyright 2017-2018, Ankit R Gadiya
# BSD 3-Clause License

# Site
lang: "en"
title: "Jekyll"
author: "Ankit R Gadiya"
url: "https://st.argp.in"
baseurl: "/jekyll"
logo: "https://github.com/simple-template.png"
permalink: "/blog/:year/:month/:day/:title/"

# micro_blog: ankit
copyright: "BSD 3-Clause License"

# SEO
# twitter:
#   username: ankitrgadiya
# social:
#   name: "Ankit R Gadiya"
#   links:
#       - https://www.facebook.com/ankit.r.gadiya
#       - https://twitter.com/ankitrgadiya
#       - https://github.com/ankitrgadiya
#       - https://www.youtube.com/channel/UCbct_i6BcaEZCqt63c-nyYA
#       - https://www.instagram.com/ankitrgadiya
#       - https://www.linkedin.com/in/ankitrgadiya
# google_site_verification:
# pocket_verification:

# Build
timezone: Asia/Kolkata
markdown: kramdown
mathjax: true
syntax_highlight: true
plugins:
    - jekyll-seo-tag
    - jekyll-feed
    - jekyll-sitemap
